cardigann/cardigann

indexer/catmap.go
indexer/catmap_test.go
indexer/filters.go
indexer/parser.go
indexer/parser_test.go
indexer/runner.go
indexer/runner_test.go
torznab/caps.go
torznab/category.go
torznab/category_test.go

Some trackers have string category id's, this adds support for mapping them back to torznab cats.

Allow strings in local catids

---

indexer/aggregate.go

Fixed `slice bounds out of range` panic when querying the aggregate indexer.

Fixed  panic when querying the aggregate indexer

---

definitions/avistaz.yml

Identical to privatehd and cinemaz so this was fast.
```
Definition file parsing OK
INFO[0000] Testing search mode "search"                 
INFO[0002] Successfully logged in                        site=avistaz
INFO[0002] Searching indexer                             query=limit=5&t=search site=avistaz
INFO[0002] Query returned 5 results                      site=avistaz time=342.475683ms
INFO[0002] Testing downloading torrent                   url=https://avistaz.to/download/torrent/52276.the.wailing.goksung.2016.limited.720p.bluray.x264.depth.torrent
INFO[0003] Downloaded 39458 bytes from linked torrent   
Indexer test returned OK
```

Added AvistaZ tracker definition

---

definitions/cinemaz.yml

Identical to privatehd so this was fast.
```
Definition file parsing OK
INFO[0000] Testing search mode "search"                 
INFO[0001] Successfully logged in                        site=cinemaz
INFO[0001] Searching indexer                             query=limit=5&t=search site=cinemaz
INFO[0001] Query returned 5 results                      site=cinemaz time=387.634108ms
INFO[0001] Testing downloading torrent                   url=https://cinemaz.to/download/torrent/14056.duffer.1971.720p.bluray.x264.ac.3.7sins.torrent
INFO[0002] Downloaded 13880 bytes from linked torrent   
Indexer test returned OK
```

Added CinemaZ tracker definition

---

README.md
definitions/immortalseed.yml

Fixes  #85
The definition is based on the work from @subzero79
Due to a cardigann limitation this definition currently ignores releases without a cover image as they won't have a tooltip contianing the full release name.
```
Definition file for immortalseed parsed OK V
Testing indexer immortalseed
Indexer immortalseed passed V
``` 
current git HEAD (--version generates no output)

Add Immortalseed tracker

---

definitions/alpharatio.yml

Fixes #62 
Prepends `searchsubmit=1` to ensure the same output regardless of default filter settings.
Test output:
```
./cardigann test definitions/alpharatio.yml 
→ Testing 1 definition(s) (dev/linux/amd64)
→ Testing indexer alpharatio at https://alpharatio.cc/
Testing login with valid credentials SUCCESS ✓ in 2.412593683s
Testing search mode "search" SUCCESS ✓ in 3.612463663s
Testing search mode "tv-search" SUCCESS ✓ in 3.274425608s
Testing empty results are handled SUCCESS ✓ in 805.457642ms
Testing ratio SUCCESS ✓ in 810.51563ms
→ Indexer alpharatio is OK
```

Fix alpharatio definition (round 2)

---

README.md
definitions/sceneaccess.yml

```
→ Testing 1 definition(s) (1.8.5-18-g8437de7/linux/amd64)
→ Testing indexer sceneaccess at https://sceneaccess.eu/
Testing login with valid credentials SUCCESS ✓ in 8.102449596s
Testing search mode "search" SUCCESS ✓ in 56.734658192s
Testing search mode "tv-search" SUCCESS ✓ in 6.880802031s
Testing empty results are handled SUCCESS ✓ in 4.557961252s
Testing ratio SUCCESS ✓ in 19.277µs
→ Indexer sceneaccess is OK
``` 
1.8.5-18-g8437de7

Added sceneaccess tracker definition

---

README.md
definitions/scenetime.yml

fixes #125
```
→ Testing 1 definition(s) (1.8.7-43-g72447b0/windows/amd64)
→ Testing indexer scenetime at https://www.scenetime.com/
Testing required config is available ←[32mSUCCESS V←[0m ←[37min 0s←[0m
Testing login with valid credentials ←[32mSUCCESS V←[0m ←[37min 287.5365ms←[0m
Testing search mode "search" ←[32mSUCCESS V←[0m ←[37min 400.0508ms←[0m
Testing search mode "tv-search" ←[32mSUCCESS V←[0m ←[37min 615.5781ms←[0m
Testing empty results are handled ←[32mSUCCESS V←[0m ←[37min 146.0185ms←[0m
Testing ratio ←[32mSUCCESS V←[0m ←[37min 100.0127ms←[0m
→ Indexer scenetime is ←[32mOK←[0m
```

Add SceneTime tracker

---

README.md
definitions/torrentsyndikat.yml

Fixes #127
```
→ Testing 1 definition(s) (1.8.7-43-g72447b0/windows/amd64)
→ Testing indexer torrentsyndikat at https://torrent-syndikat.org/
Testing required config is available ←[32mSUCCESS V←[0m ←[37min 0s←[0m
Testing login with valid credentials ←[32mSUCCESS V←[0m ←[37min 304.0387ms←[0m
Testing search mode "search" ←[32mSUCCESS V←[0m ←[37min 2.9088694s←[0m
Testing search mode "tv-search" ←[32mSUCCESS V←[0m ←[37min 709.5901ms←[0m
Testing empty results are handled ←[32mSUCCESS V←[0m ←[37min 729.0926ms←[0m
Testing ratio ←[32mSUCCESS V←[0m ←[37min 760.5966ms←[0m
→ Indexer torrentsyndikat is ←[32mOK←[0m
```

Add Torrent-Syndikat tracker

---

README.md
definitions/funfile.yml

fixes #150
```
→ Testing 1 definition(s) (1.9.2/windows/amd64)
→ Testing indexer funfile at https://www.funfile.org/
Testing required config is available SUCCESS V in 500.1µs
Testing login with valid credentials SUCCESS V in 5.2941723s
Testing search mode "search" SUCCESS V in 20.0840503s
Testing search mode "tv-search" SUCCESS V in 17.8022606s
Testing empty results are handled SUCCESS V in 5.6127127s
Testing ratio SUCCESS V in 5.9857601s
→ Indexer funfile is OK
``` 
If you run into issues with testing, remember you can run a debug test with `cardigann test --debug --cachepages definitions/trackername.yml`.

add FunFile tracker

---

definitions/iptorrents.yml
definitions/morethantv.yml
indexer/runner.go
indexer/selector.go
torznab/result.go

files: Number of files
grabs: Number of times item downloaded
downloadvolumefactor: factor for the download volume, in most cases it should be set to 1, if a torrent is set to freeleech set it to 0, if only 50% is counted set it to 0.5
uploadvolumefactor: factor for the upload volume, in most cases it should be set to 1, if a torrent is set to neutral leech (upload is not counted) set it to 0, if it's set to double upload set it to 2
Besides the attributes the behavior of "case" has been slightly modified:
The pattern doesn't need to be an exact match any longer.
This makes writing cases for downloadvolumefactor/uploadvolumefactor easier

Add missing torznab attributes files, grabs, downloadvolumefactor, uploadvolumefactor

---

indexer/runner.go

Sonarr(nzbdrone) will call cardigann API with tvdb=0, it returns an error back
```xml
<error>
<code>900</code>
<description>
json: cannot unmarshal number into Go value of type string
</description>
</error>
```
Digging in the issue, looks like http client in tvmaze/client.go tries to call tvmaze ( http://api.tvmaze.com/lookup/shows?thetvdb=0 ), which returns:
```javascript
{
"name": "Bad Request",
"message": "",
"code": 0,
"status": 400
}
```
Although probably adding error handling would be a better solution, I felt that with tvdb=0 the client should not even make the call in the first place.

fix indexer error when tvdb is 0

---

README.md
definitions/transmithenet.yml

Fix #112
```
→ Testing 1 definition(s) (1.9.3/windows/amd64)
→ Testing indexer transmithenet at https://transmithe.net
Testing required config is available SUCCESS V in 1.0001ms
Testing login with valid credentials SUCCESS V in 1.1131413s
Testing search mode "search" SUCCESS V in 4.5110728s
Testing search mode "tv-search" SUCCESS V in 4.0885192s
Testing empty results are handled SUCCESS V in 917.6165ms
Testing ratio SUCCESS V in 0s
→ Indexer transmithenet is OK
```

Add Transmithe.net tracker

---

README.md
definitions/shareisland.yml

Fix #69
```
→ Testing 1 definition(s) (1.9.3/windows/amd64)
→ Testing indexer shareisland at http://shareisland.org
Testing required config is available SUCCESS V in 500µs
Testing login with valid credentials SUCCESS V in 1.2661608s
Testing search mode "search" SUCCESS V in 8.5690882s
Testing search mode "tv-search" SUCCESS V in 9.7752413s
Testing empty results are handled SUCCESS V in 1.8537354s
Testing ratio SUCCESS V in 2.4318088s
→ Indexer shareisland is OK
```

Add Shareisland tracker

---

README.md
definitions/bitmetv.yml
definitions/funfile.yml
definitions/hdspace.yml
definitions/scenetime.yml
definitions/shareisland.yml
definitions/transmithenet.yml
definitions/worldofp2p.yml
indexer/runner.go
torrentpotato/server.go

```
→ Testing 1 definition(s) (1.9.3/windows/amd64)
→ Testing indexer worldofp2p at https://worldofp2p.net
Testing required config is available SUCCESS V in 1.5002ms
Testing login with valid credentials SUCCESS V in 1.1676483s
Testing search mode "search" SUCCESS V in 5.6902225s
Testing search mode "tv-search" SUCCESS V in 4.9361268s
Testing empty results are handled SUCCESS V in 1.2476584s
Testing ratio SUCCESS V in 962.1222ms
→ Indexer worldofp2p is OK
```

Add WorldOfP2P tracker

---

README.md
definitions/tspate.yml

Fix #161 
```
→ Testing 1 definition(s) (1.9.3-20-g871e7c1/windows/amd64)
→ Testing indexer tspate at https://www.tspate.me/
Testing required config is available SUCCESS V in 500.1µs
Testing login with valid credentials SUCCESS V in 3.157901s
Testing search mode "search" SUCCESS V in 3.1323978s
Testing search mode "tv-search" SUCCESS V in 1.6317072s
Testing empty results are handled SUCCESS V in 471.0599ms
Testing ratio SUCCESS V in 503.0638ms
→ Indexer tspate is OK
```

Add Tspate tracker

---

README.md
definitions/eotforum.yml

```
→ Testing 1 definition(s) (1.9.4-8-gbcefd47/windows/amd64)
→ Testing indexer eotforum at http://eot-forum.net
Testing required config is available SUCCESS V in 2.0003ms
Testing login with valid credentials SUCCESS V in 2.8228585s
Testing search mode "search" SUCCESS V in 14.7313707s
Testing search mode "tv-search" SUCCESS V in 14.6798641s
Testing empty results are handled SUCCESS V in 3.3274226s
Testing ratio SUCCESS V in 3.9490014s
→ Indexer eotforum is OK
```

Add EoT-Forum tracker

---

indexer/runner.go

Add `replace` function to templates.
Example usage: `'{{replace .Keywords " " "*" -1}}'`

Add replace function to template

---

indexer/filters.go

Some providers like ilcorsaronero.info require "magnet:?xt=urn:btih:" prefix for download, exposing only the hash of the magnet url

Added Prepend functions to filters

---

server/handler.go

It's not safe to assume the title is a filename because it may contain characters not valid for a filename. Removing / prevents a valid title to break the "/download/" route, but further sanitization is required.

Remove "/" from title before using as filename.

---

definitions/torrentz2.yml

I tried adding append filter with &dn={{ .Result.title }}.torrent, like Jackett definition, so added torrent has name before downloading metadata, but it didn't work in cardigann, I guess cardigann doesn't support template in filters args.

add categories from Jackett#1047

---

definitions/alpharatio.yml

Category parameter changed to `filter_cat[7]=1` where 7 is the category name.

Fix bug with alpharatio category parsing, closes #394

---

README.md
definitions/yggtorrent.yml

I mixed multiple sources for inspiration. Categories mappings are sometimes wild guesses...  Anyway it has been working for weeks with sonarr (radarr does not seem to "like" torznab/cardigann/my setup).
```
→ Testing 1 definition(s) (1.9.10-6-g70a254b/linux/amd64)
→ Testing indexer yggtorrent at https://yggtorrent.com
Testing required config is available SUCCESS ✓ in 2.037568ms
Testing login with valid credentials SUCCESS ✓ in 1.511097921s
Testing search mode "search" SUCCESS ✓ in 3.011206487s
Testing search mode "tv-search" SUCCESS ✓ in 2.33056293s
Testing empty results are handled SUCCESS ✓ in 519.316115ms
Testing ratio SUCCESS ✓ in 49.288µs
→ Indexer yggtorrent is OK
``` 
It should close #403

Add Yggtorrent indexer

---

definitions/yggtorrent.yml

It should fix yggtorrent indexer returning no results
- [✓ ] Run `cardigann test definitions/yggtorrent.yml` and include the output here:
```
→ Testing 1 definition(s) (1.10.1-9-g1501db7/linux/amd64)
→ Testing indexer yggtorrent at https://yggtorrent.is
Testing required config is available SUCCESS ✓ in 2.488868ms
Testing login with valid credentials SUCCESS ✓ in 1.273291452s
Testing search mode "search" SUCCESS ✓ in 1.568619116s
Testing search mode "tv-search" SUCCESS ✓ in 1.768690191s
Testing search mode "movie-search" SUCCESS ✓ in 1.436137122s
Testing empty results are handled SUCCESS ✓ in 339.469246ms
Testing ratio SUCCESS ✓ in 1.28311ms
→ Indexer yggtorrent is OK
``` 
- [ ✓] Indexer already in the README

Fix yggtorrent after DNS and design changes

---

web/src/Login.js

The prefix path (e.g. `/cardigann/`) isn't respected when passphrases are used. The absolute URL of `/xhr/..` is used instead of the relative path `./xhr/..`

Fix passphrase auth with non-root prefixes

---

definitions/yggtorrent.yml

This PR fixes the parsing of the size field in results after a change on the yggtorrent side...
→ Testing 1 definition(s) (1.10.1-9-g1501db7/linux/amd64)
→ Testing indexer yggtorrent at https://yggtorrent.is
Testing required config is available SUCCESS ✓ in 2.871409ms
Testing login with valid credentials SUCCESS ✓ in 1.272973104s
Testing search mode "search" SUCCESS ✓ in 1.684820174s
Testing search mode "tv-search" SUCCESS ✓ in 2.005779229s
Testing search mode "movie-search" SUCCESS ✓ in 1.566366819s
Testing empty results are handled SUCCESS ✓ in 363.027111ms
Testing ratio SUCCESS ✓ in 40.743µs
→ Indexer yggtorrent is OK
Should fix #434

Fix size units in yggtorrent results

---

README.md
definitions/metaltracker.yml

Inspired by Jackett and comments in the related issue. 
Date has been set to "today" which appears as "in an hour".
Not yet tested with headphones...
```
→ Testing 1 definition(s) (1.9.10-6-g70a254b/linux/amd64)
→ Testing indexer metaltracker at http://en.metal-tracker.com/
Testing required config is available SUCCESS ✓ in 2.164954ms
Testing login with valid credentials SUCCESS ✓ in 1.767531041s
Testing search mode "search" SUCCESS ✓ in 2.650540518s
Testing search mode "music-search" SUCCESS ✓ in 2.430225372s
Testing empty results are handled SUCCESS ✓ in 865.36451ms
Testing ratio SUCCESS ✓ in 174.579µs
→ Indexer metaltracker is OK
``` 
It may close #375

Add metal-tracker.com Indexer

---

definitions/torrentday.yml
indexer/runner.go

* Result table: `td.t_label` was changed to `td.torrentNameInfo`
* Made label selector use `nth-child` to be consistent with others
* Added workaround for Cloudflare browser check

Updated TorrentDay definition
