cardigann/cardigann

- Dockerfile
- Makefile
- config/dirs.go
- docker-compose.yml
- indexer/definitions.go
- indexer/load.go
- main.go
- server/handler.go
- server/xhr.go
This bundles definitions into the binary so that users don't have to download definitions if they don't want to.
> Bundle definitions into binary

- definitions/speedcd.yml
> Add speedcd definition

- definitions/alpharatio.yml
- definitions/beyondhd.yml
- definitions/bithdtv.yml
- definitions/demonoid.yml
- definitions/filelist.yml
- definitions/freshon.yml
- definitions/hdtorrents.yml
- definitions/iptorrents.yml
- definitions/morethantv.yml
- definitions/torrentday.yml
- definitions/torrentleech.yml
- indexer/parser.go
- indexer/parser_test.go
- indexer/runner.go
- indexer/runner_test.go
- indexer/tester.go
- main.go
This adds support for scraping ratios from the various trackers and exposing them via the command line.
> Add a command to fetch ratio for an indexer

- definitions/privatehd.yml
```
Definition file parsing OK
INFO[0000] Testing search mode "search"                 
INFO[0001] Successfully logged in                        site=privatehd
INFO[0001] Searching indexer                             query=limit=5&t=search site=privatehd
INFO[0002] Query returned 5 results                      site=privatehd time=676.67974ms
INFO[0002] Testing downloading torrent                   url=https://privatehd.to/download/torrent/12684.once.upon.a.time.s05.1080p.bluray.dts.x264.rovers.torrent
INFO[0003] Downloaded 98701 bytes from linked torrent   
Indexer test returned OK
```
> Added PrivateHD tracker

- definitions/hdarea.yml
I'm not 100% sure with the categories but apart form that it works fine.
> Support for the HDArea.co  tracker.

- definitions/bitmetv.yml
> Add BitMeTV tracker support

- definitions/privatehd.yml
Removed "www" from the url because it does a redirection and it doesn't work with it.
> Removed "www" from the url

- README.md
- definitions/hdme.yml
fixes #56 
```
Definition file for hdme parsed OK V
Testing indexer hdme
Indexer hdme passed V
``` 
current git HEAD (--version generates no output)
> Add HDME tracker

- definitions/alpharatio.yml
> Update alpharatio definition

- README.md
- definitions/torrentbytes.yml
- [x ] Run `cardigann test definitions/trackername.yml` and include the output here:
```
Definition file for torrentbytes parsed OK ✓
Testing indexer torrentbytes
Indexer torrentbytes passed ✓
``` 
- [x ] Post the version of cardigann you tested this with (from the footer of the web interface or `cardigann --version`)
1.8.5
- [x ] Make sure to add the indexer to the list in the README
> Added Torrentbytes definition

- README.md
- definitions/danishbits.yml
```
→ Testing 1 definition(s) (dev/darwin/amd64)
→ Testing indexer danishbits at https://danishbits.org
Testing required config is available SUCCESS ✓ in 374.961µs
Testing login with valid credentials SUCCESS ✓ in 5.265800035s
Testing search mode "search" SUCCESS ✓ in 5.441287009s
Testing search mode "tv-search" SUCCESS ✓ in 5.207596494s
Testing empty results are handled SUCCESS ✓ in 1.637820132s
Testing ratio SUCCESS ✓ in 1.160914925s
→ Indexer danishbits is OK
```
> Implement danishbits tracker

- definitions/funfile.yml
> Fix FunFile ratio

- definitions/bitmetv.yml
> Update bitmetv definition

- definitions/hdspace.yml
> Fix HD-Space login test

- definitions/scenetime.yml
> Fix SceneTime

- README.md
- definitions/abnormal.yml
New French Private Tracker
```
PS D:\Projets\cardigann> ./cardigann test definitions/abnormal.yml
→ Testing 1 definition(s) (1.9.3-26-g5ab1db2/windows/amd64)
→ Testing indexer abnormal at https://abnormal.ws
Testing required config is available SUCCESS ✓ in 987.5µs
Testing login with valid credentials SUCCESS ✓ in 1.0367229s
Testing search mode "search" SUCCESS ✓ in 1.8276642s
Testing search mode "tv-search" SUCCESS ✓ in 1.6494353s
Testing empty results are handled SUCCESS ✓ in 395.2279ms
Testing ratio SUCCESS ✓ in 1.5173ms
→ Indexer abnormal is OK
```
> Add Abnormal Tracker

- definitions/eztv.yml
Fixed eztv definition, which downloaded episode page instead of torrent file.
> fix eztv definition

- definitions/xthor.yml
> Change Xthor Tracker login method to POST

- README.md
- indexer/filters.go
Updated README.MD  with "How to compile (linux)"
Added **prepend** filter to filters.go
> Updated README.MD and Added prepend filter

- indexer/runner.go
- vendor/github.com/cardigann/go-imdb-scraper/README.md
- vendor/github.com/cardigann/go-imdb-scraper/scrape.go
- vendor/github.com/cardigann/go-imdb-scraper/scrape_test.go
- vendor/vendor.json
Fix searching by imdb identifier
> Fix search by imdb identifier

- definitions/torrentday.yml
> Update torrent day definition
